name: Easy Twitter Login
description: Courtesy of <a href="http://www.5twentystudios.com">5Twenty STudios</a>, allows users to login via twitter into the croogo system.

author: Jonathon Byrd
authorEmail: support@5twentystudios.com
authorUrl: http://5twentystudios.com

dependencies:
  plugins: